apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-news-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: project.abhimanyu.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fake-news-service
            port:
              number: 80
