apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-news-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fake-news.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fake-news-service   # Your service name
                port:
                  number: 80              # Your service port
