apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-news-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx          # if you have multiple ingress controllers
  rules:
    - host: project.abhimanyu.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fake-news-service
                port:
                  number: 80   # ← service port, not 5000
  # (Optional) TLS block if you’ve set up cert-manager / TLS secrets
  # tls:
  #   - hosts:
  #       - project.abhimanyu.live
  #     secretName: fake-news-tls
