apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-news-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 13-201-137-1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fake-news-service
                port:
                  number: 80
