apiVersion: v1
kind: Service
metadata:
  name: fake-news-service
spec:
  selector:
    app: fake-news
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 81
    targetPort: 5000
    nodePort: 31159
