name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fake-news-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fake-news-app:latest

  deploy-to-minikube:
    needs: build-and-push
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Ensure Minikube is running
        run: |
          if ! minikube status | grep -q "Running"; then
            minikube start --driver=docker
          fi

      - name: Set kube context to Minikube
        run: kubectl config use-context minikube

      - name: Delete existing resources (clean-up)
        continue-on-error: true
        run: |
          kubectl delete -f k8s/ingress.yaml
          kubectl delete -f k8s/service.yaml
          kubectl delete -f k8s/deployment.yaml

      - name: Apply Kubernetes manifests (deployment, service, ingress)
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Wait for Ingress to be ready
        run: |
          sleep 10
          kubectl get ingress
